#!/usr/bin/env python3
"""
Build method-performance summary tables from target-centric and reported-taxa
long tables.

This wrapper preserves the current target-centric benchmarking workflow and
adds support for a second reported-taxa long table so that genuine off-target
and cross-hit species can be summarised without overloading the original
`combined_long.tsv` logic.

Inputs
------
- combined_long.tsv
  The existing target-centric long table used for method benchmarking.
- reported_taxa_long.tsv
  An optional taxon-centric long table produced by the updated spike-in
  summariser. When provided, this is used to build the verbose
  "All reported species / off-target species" table.

Outputs
-------
All original outputs are retained, and two additional outputs are written when
reported taxa are available:

- reported_offtarget_species_summary.tsv
- reported_taxa_detection_calls.tsv

The HTML page and fragment also include the reported/off-target table.
"""

from __future__ import annotations

import argparse
import html
import importlib.util
import math
import sys
from pathlib import Path
from typing import Optional

import pandas as pd


def load_base_module():
    """
    Load the original performance-table module from the same directory.

    Returns
    -------
    module
        Imported base module.
    """
    this_path = Path(__file__).resolve()
    base_path = this_path.with_name("build_method_performance_table_with_offtargets.py")
    if not base_path.exists():
        raise FileNotFoundError(
            f"Required base script not found next to wrapper: {base_path}"
        )

    spec = importlib.util.spec_from_file_location(
        "build_method_performance_table_with_offtargets_base",
        str(base_path),
    )
    if spec is None or spec.loader is None:
        raise ImportError(f"Could not load module spec for {base_path}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


BASE = load_base_module()


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.

    Returns
    -------
    argparse.Namespace
        Parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Build method-level performance summaries from combined_long.tsv "
            "and, optionally, reported_taxa_long.tsv."
        )
    )
    parser.add_argument("--combined_long_tsv", required=True)
    parser.add_argument(
        "--reported_taxa_long_tsv",
        required=False,
        default=None,
        help=(
            "Optional reported_taxa_long.tsv generated by the updated spike-in "
            "summariser. When provided, this drives the reported/off-target "
            "species table."
        ),
    )
    parser.add_argument("--out_dir", required=True)
    parser.add_argument(
        "--threshold_mode",
        choices=["fixed", "baseline_mean", "baseline_max", "baseline_mean_plus_sd"],
        default="baseline_max",
    )
    parser.add_argument("--min_detect_value", type=float, default=1.0)
    parser.add_argument("--sd_multiplier", type=float, default=2.0)
    return parser.parse_args()


def normalise_reported_taxa_long(dataframe: pd.DataFrame) -> pd.DataFrame:
    """
    Normalise the reported-taxa long table.

    Parameters
    ----------
    dataframe : pd.DataFrame
        Raw reported-taxa long table.

    Returns
    -------
    pd.DataFrame
        Normalised reported-taxa long table.
    """
    required = {
        "workflow_type",
        "run_name",
        "taxon_name",
        "metric_name",
        "metric_value",
    }
    missing = required - set(dataframe.columns)
    if missing:
        raise ValueError(
            "reported_taxa_long.tsv is missing required columns: "
            + ", ".join(sorted(missing))
        )

    out_df = dataframe.copy()

    rename_map = {}
    if "workflow_type" in out_df.columns:
        rename_map["workflow_type"] = "workflow"
    if rename_map:
        out_df = out_df.rename(columns=rename_map)

    if "classifier" not in out_df.columns:
        out_df["classifier"] = "unknown_classifier"
    if "report_tsv" not in out_df.columns:
        out_df["report_tsv"] = pd.NA
    if "filter_prefix" not in out_df.columns:
        out_df["filter_prefix"] = pd.NA
    if "matched_target_labels" not in out_df.columns:
        out_df["matched_target_labels"] = ""
    if "replicate" not in out_df.columns:
        out_df["replicate"] = pd.NA
    if "spike_n_per_genome" not in out_df.columns:
        out_df["spike_n_per_genome"] = pd.NA
    if "total_spike_n" not in out_df.columns:
        out_df["total_spike_n"] = out_df["spike_n_per_genome"]
    if "n_genomes" not in out_df.columns:
        out_df["n_genomes"] = pd.NA
    if "is_shuffled_control" not in out_df.columns:
        out_df["is_shuffled_control"] = False

    out_df["workflow"] = out_df["workflow"].fillna("unknown").astype(str)
    out_df["run_name"] = out_df["run_name"].fillna("unknown_run").astype(str)
    out_df["classifier"] = out_df["classifier"].fillna("unknown_classifier").astype(str)
    out_df["taxon_name"] = out_df["taxon_name"].fillna("unknown_taxon").astype(str)
    out_df["metric_name"] = out_df["metric_name"].fillna("unknown_metric").astype(str)
    out_df["matched_target_labels"] = (
        out_df["matched_target_labels"].fillna("").astype(str)
    )

    numeric_columns = [
        "metric_value",
        "replicate",
        "spike_n_per_genome",
        "total_spike_n",
        "n_genomes",
        "percent",
    ]
    for column in numeric_columns:
        if column in out_df.columns:
            out_df[column] = pd.to_numeric(out_df[column], errors="coerce")

    out_df["is_shuffled_control"] = (
        out_df["is_shuffled_control"]
        .fillna(False)
        .astype(str)
        .str.lower()
        .isin(["true", "1", "yes"])
    )

    if "total_spike_n" in out_df.columns:
        out_df["spike_n"] = pd.to_numeric(out_df["total_spike_n"], errors="coerce")
    else:
        out_df["spike_n"] = pd.to_numeric(
            out_df["spike_n_per_genome"], errors="coerce"
        )

    out_df["is_positive"] = (~out_df["is_shuffled_control"]) & (out_df["spike_n"] > 0)
    out_df["is_negative"] = out_df["is_shuffled_control"] | (out_df["spike_n"] == 0)

    return out_df


def choose_reported_taxa_metric(dataframe: pd.DataFrame) -> pd.DataFrame:
    """
    Restrict to the primary count metric used for taxa-level thresholding.

    Parameters
    ----------
    dataframe : pd.DataFrame
        Normalised reported-taxa long table.

    Returns
    -------
    pd.DataFrame
        Subset restricted to reported clade reads.
    """
    metric_mask = dataframe["metric_name"].astype(str).str.endswith("_reported_clade_reads")
    subset = dataframe.loc[metric_mask].copy()
    if subset.empty:
        subset = dataframe.copy()
    return subset


def compute_reported_taxa_detection_calls(
    reported_taxa_df: pd.DataFrame,
    threshold_mode: str,
    min_detect_value: float,
    sd_multiplier: float,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Compute taxa-level detection calls from the reported-taxa long table.

    Parameters
    ----------
    reported_taxa_df : pd.DataFrame
        Reported-taxa long table.
    threshold_mode : str
        Threshold rule.
    min_detect_value : float
        Minimum detection threshold.
    sd_multiplier : float
        Standard-deviation multiplier for baseline_mean_plus_sd mode.

    Returns
    -------
    tuple[pd.DataFrame, pd.DataFrame]
        Detection call table and threshold table.
    """
    if reported_taxa_df.empty:
        return pd.DataFrame(), pd.DataFrame()

    detection_rows: list[pd.DataFrame] = []
    threshold_rows: list[dict[str, object]] = []

    grouped = reported_taxa_df.groupby(
        ["workflow", "classifier", "taxon_name", "metric_name"],
        dropna=False,
    )

    for (workflow, classifier, taxon_name, metric_name), group in grouped:
        negatives = group.loc[group["is_negative"], "metric_value"]
        threshold_value = BASE.choose_threshold(
            negative_values=negatives,
            threshold_mode=threshold_mode,
            min_detect_value=min_detect_value,
            sd_multiplier=sd_multiplier,
        )
        group = group.copy()
        group["threshold_value"] = threshold_value
        group["detected"] = group["metric_value"] >= threshold_value
        detection_rows.append(group)
        threshold_rows.append(
            {
                "workflow": workflow,
                "classifier": classifier,
                "taxon_name": taxon_name,
                "metric_name": metric_name,
                "threshold_mode": threshold_mode,
                "threshold_value": threshold_value,
                "negative_mean": float(negatives.mean())
                if not negatives.dropna().empty
                else math.nan,
                "negative_max": float(negatives.max())
                if not negatives.dropna().empty
                else math.nan,
                "negative_sd": float(negatives.std(ddof=0))
                if not negatives.dropna().empty
                else math.nan,
                "n_negative_for_threshold": int(negatives.dropna().shape[0]),
            }
        )

    detection_df = (
        pd.concat(detection_rows, ignore_index=True)
        if detection_rows
        else pd.DataFrame()
    )
    threshold_df = pd.DataFrame(threshold_rows)
    return detection_df, threshold_df


def expected_species_map_from_combined_long(
    combined_long_df: pd.DataFrame,
) -> dict[tuple[str, str], list[str]]:
    """
    Build a map of expected species per workflow/run from the target-centric
    long table.

    Parameters
    ----------
    combined_long_df : pd.DataFrame
        Normalised combined long table.

    Returns
    -------
    dict[tuple[str, str], list[str]]
        Mapping from (workflow, run_name) to sorted expected species list.
    """
    if combined_long_df.empty:
        return {}

    positive_df = combined_long_df.loc[combined_long_df["is_positive"]].copy()
    if positive_df.empty:
        return {}

    mapping: dict[tuple[str, str], list[str]] = {}
    grouped = positive_df.groupby(["workflow", "run_name"], dropna=False)
    for (workflow, run_name), group in grouped:
        species = sorted(pd.unique(group["target_label"].astype(str)))
        mapping[(str(workflow), str(run_name))] = species
    return mapping


def build_reported_species_summary_from_taxa(
    reported_detection_df: pd.DataFrame,
    reported_threshold_df: pd.DataFrame,
    expected_species_map: dict[tuple[str, str], list[str]],
) -> pd.DataFrame:
    """
    Build a verbose run-level table of all reported species and off-target hits
    using the genuine reported-taxa long table.

    Parameters
    ----------
    reported_detection_df : pd.DataFrame
        Taxa-level detection call table.
    reported_threshold_df : pd.DataFrame
        Taxa-level threshold table.
    expected_species_map : dict[tuple[str, str], list[str]]
        Expected species per workflow/run derived from combined_long.tsv.

    Returns
    -------
    pd.DataFrame
        Verbose reported/off-target species summary.
    """
    if reported_detection_df.empty:
        return pd.DataFrame()

    rows: list[dict[str, object]] = []
    grouped = reported_detection_df.groupby(
        ["workflow", "classifier", "run_name"],
        dropna=False,
    )

    for (workflow, classifier, run_name), run_df in grouped:
        expected_species = expected_species_map.get(
            (str(workflow), str(run_name)),
            [],
        )

        all_species = sorted(pd.unique(run_df["taxon_name"].astype(str)))

        reported_any = sorted(
            pd.unique(
                run_df.loc[run_df["detected"] == True, "taxon_name"].astype(str)
            )
        )
        reported_positive = sorted(
            pd.unique(
                run_df.loc[
                    (run_df["is_positive"]) & (run_df["detected"] == True),
                    "taxon_name",
                ].astype(str)
            )
        )
        reported_negative = sorted(
            pd.unique(
                run_df.loc[
                    (run_df["is_negative"]) & (run_df["detected"] == True),
                    "taxon_name",
                ].astype(str)
            )
        )

        off_target_any = [x for x in reported_any if x not in expected_species]
        off_target_positive = [x for x in reported_positive if x not in expected_species]
        off_target_negative = [x for x in reported_negative if x not in expected_species]
        missing_expected = [x for x in expected_species if x not in reported_positive]

        threshold_rows = reported_threshold_df.loc[
            (reported_threshold_df["workflow"] == workflow)
            & (reported_threshold_df["classifier"] == classifier)
        ].copy()
        threshold_values = pd.to_numeric(
            threshold_rows["threshold_value"], errors="coerce"
        ).dropna()
        min_threshold = (
            float(threshold_values.min()) if not threshold_values.empty else math.nan
        )

        species_detail: list[str] = []
        for species in all_species:
            species_df = run_df.loc[run_df["taxon_name"] == species].copy()
            n_observations = int(species_df.shape[0])
            n_detected = int((species_df["detected"] == True).sum())
            pos_detected = int(
                ((species_df["is_positive"]) & (species_df["detected"] == True)).sum()
            )
            neg_detected = int(
                ((species_df["is_negative"]) & (species_df["detected"] == True)).sum()
            )
            detection_rate = BASE.safe_divide(n_detected, n_observations)
            metric_name = (
                str(species_df["metric_name"].dropna().iloc[0])
                if not species_df["metric_name"].dropna().empty
                else "unknown_metric"
            )
            threshold_row = reported_threshold_df.loc[
                (reported_threshold_df["workflow"] == workflow)
                & (reported_threshold_df["classifier"] == classifier)
                & (reported_threshold_df["taxon_name"] == species)
                & (reported_threshold_df["metric_name"] == metric_name)
            ]
            threshold_value = (
                float(threshold_row.iloc[0]["threshold_value"])
                if not threshold_row.empty
                else math.nan
            )
            species_detail.append(
                f"{species}: detected={n_detected}/{n_observations}, "
                f"positive={pos_detected}, negative={neg_detected}, "
                f"threshold={BASE.format_value(threshold_value)}, "
                f"rate={BASE.format_value(detection_rate)}"
            )

        if reported_any and not off_target_any and not missing_expected:
            interpretation = "Only expected tracked species reported"
        elif reported_any and off_target_any:
            interpretation = "Off-target species also reported"
        elif not reported_any:
            interpretation = "No species reported above threshold"
        else:
            interpretation = "Partial expected-species recovery"

        rows.append(
            {
                "Workflow": workflow,
                "Classifier": classifier,
                "Run": run_name,
                "Expected species": "; ".join(expected_species),
                "All reported species": "; ".join(reported_any),
                "Reported species in positives": "; ".join(reported_positive),
                "Reported species in negatives": "; ".join(reported_negative),
                "Off-target species": "; ".join(off_target_any),
                "Off-target species in positives": "; ".join(off_target_positive),
                "Off-target species in negatives": "; ".join(off_target_negative),
                "Missing expected species": "; ".join(missing_expected),
                "N expected species": len(expected_species),
                "N reported species": len(reported_any),
                "N off-target species": len(off_target_any),
                "Detection metric": "reported_clade_reads",
                "Min threshold": min_threshold,
                "Interpretation": interpretation,
                "Reported species detail": " | ".join(species_detail),
                "Note": (
                    "This table is derived from reported_taxa_long.tsv and so "
                    "retains genuine reported taxa rather than only tracked "
                    "target labels."
                ),
            }
        )

    reported_df = pd.DataFrame(rows)
    if reported_df.empty:
        return reported_df

    reported_df = reported_df.sort_values(
        by=["N off-target species", "N reported species", "Workflow", "Classifier", "Run"],
        ascending=[False, False, True, True, True],
    ).reset_index(drop=True)
    reported_df.insert(0, "Rank", range(1, len(reported_df) + 1))
    return reported_df


def build_html_page(
    compact_df: pd.DataFrame,
    panel_species_df: pd.DataFrame,
    reported_species_df: pd.DataFrame,
    method_df: pd.DataFrame,
    by_spike_df: pd.DataFrame,
    definitions_df: pd.DataFrame,
    plot_explanations_df: pd.DataFrame,
) -> str:
    """
    Build the standalone HTML page.

    Returns
    -------
    str
        HTML page as a string.
    """
    style = """
    <style>
      body {
        font-family: Arial, Helvetica, sans-serif;
        margin: 0;
        padding: 0;
        color: #1a1a1a;
        background: #f7f9fc;
      }
      .container {
        max-width: 1520px;
        margin: 0 auto;
        padding: 32px;
        background: #ffffff;
      }
      h1, h2, h3 {
        color: #1f4e79;
      }
      .table-wrap {
        overflow-x: auto;
        border: 1px solid #dbe5f0;
        border-radius: 10px;
        margin-top: 14px;
        background: #ffffff;
      }
      .compact-wrap {
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
      }
      .data-table {
        width: 100%;
        border-collapse: collapse;
        font-size: 14px;
      }
      .data-table thead th {
        position: sticky;
        top: 0;
        background: #1f4e79;
        color: white;
        text-align: left;
        padding: 10px 8px;
        white-space: nowrap;
        z-index: 2;
      }
      .data-table td {
        border-bottom: 1px solid #e6edf5;
        padding: 8px;
        vertical-align: top;
        white-space: nowrap;
      }
      .data-table tbody tr:nth-child(even) {
        background: #fbfdff;
      }
      .muted {
        color: #666666;
      }
      .section-note {
        margin-top: 8px;
        color: #333333;
      }
      .small-note {
        font-size: 13px;
        color: #555555;
      }
      .cell-good {
        background: #e9f7ef;
        font-weight: 600;
      }
      .cell-mid {
        background: #fff8e1;
      }
      .cell-bad {
        background: #fdecea;
      }
      .cell-empty {
        color: #999999;
      }
      details {
        margin-top: 18px;
      }
      summary {
        cursor: pointer;
        font-weight: 600;
        color: #1f4e79;
      }
    </style>
    """

    compact_table = BASE.dataframe_to_html_table(compact_df, compact=True)
    panel_species_table = BASE.dataframe_to_html_table(panel_species_df, compact=True)
    reported_species_table = BASE.dataframe_to_html_table(
        reported_species_df,
        compact=True,
    )
    method_table = BASE.dataframe_to_html_table(method_df, compact=False)
    by_spike_table = BASE.dataframe_to_html_table(by_spike_df, compact=False)
    definitions_table = BASE.dataframe_to_html_table(definitions_df, compact=False)
    plot_table = BASE.dataframe_to_html_table(plot_explanations_df, compact=False)

    return f"""<!DOCTYPE html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <title>Method performance summary</title>
  {style}
</head>
<body>
  <div class=\"container\">
    <h1>Method performance summary</h1>
    <p class=\"muted\">
      Positive observations are non-shuffled rows with spike_n greater than 0.
      Negative observations are shuffled-control rows or rows with spike_n equal
      to 0. Detection is called using the selected threshold rule.
    </p>

    <h2>Headline comparison table</h2>
    <p class=\"section-note\">
      This compact table is intended for rapid comparison across methods.
      Methods are ranked primarily by balanced accuracy, then specificity,
      then false-positive rate, then sensitivity, then LOD.
    </p>
    {compact_table}

    <h2>Panel species summary</h2>
    <p class=\"section-note\">
      This table shows the full set of species expected in each run panel and
      the set of tracked target species that were actually found under the
      chosen threshold rule.
    </p>
    {panel_species_table}

    <h2>All reported species / off-target species</h2>
    <p class=\"section-note\">
      This table is derived from reported_taxa_long.tsv and lists the genuine
      reported taxa retained in the classifier report sidecars.
    </p>
    {reported_species_table}

    <details open>
      <summary>Show full method-level performance table</summary>
      <p class=\"small-note\">
        This detailed table includes confusion counts, threshold statistics,
        and the full set of derived performance metrics.
      </p>
      {method_table}
    </details>

    <details>
      <summary>Show detection rate by spike level</summary>
      <p class=\"small-note\">
        This table shows how often each method is called positive at each spike
        level among positive observations.
      </p>
      {by_spike_table}
    </details>

    <h2>Definitions of reported performance statistics</h2>
    {definitions_table}

    <h2>How to interpret the plots in the HTML report</h2>
    {plot_table}
  </div>
</body>
</html>
"""


def build_html_fragment(
    compact_df: pd.DataFrame,
    panel_species_df: pd.DataFrame,
    reported_species_df: pd.DataFrame,
    method_df: pd.DataFrame,
    definitions_df: pd.DataFrame,
    plot_explanations_df: pd.DataFrame,
) -> str:
    """
    Build an embeddable HTML fragment.

    Returns
    -------
    str
        HTML fragment as a string.
    """
    compact_table = BASE.dataframe_to_html_table(compact_df, compact=True)
    panel_species_table = BASE.dataframe_to_html_table(panel_species_df, compact=True)
    reported_species_table = BASE.dataframe_to_html_table(
        reported_species_df,
        compact=True,
    )
    method_table = BASE.dataframe_to_html_table(method_df, compact=False)
    definitions_table = BASE.dataframe_to_html_table(definitions_df, compact=False)
    plot_table = BASE.dataframe_to_html_table(plot_explanations_df, compact=False)

    return f"""
<section class=\"report-section\">
  <h2>Method performance summary</h2>
  <p class=\"muted\">
    Sensitivity, recall, and true positive rate are equivalent here and are
    all reported for convenience. Thresholding is method-specific and based on
    the selected negative-control rule.
  </p>

  <h3>Headline comparison table</h3>
  {compact_table}

  <h3>Panel species summary</h3>
  {panel_species_table}

  <h3>All reported species / off-target species</h3>
  {reported_species_table}

  <details>
    <summary>Show full detail table</summary>
    {method_table}
  </details>

  <h3>Definitions of reported statistics</h3>
  {definitions_table}

  <h3>How to interpret the plots</h3>
  {plot_table}
</section>
"""


def main() -> None:
    """
    Run the workflow.
    """
    args = parse_args()

    out_dir = Path(args.out_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    combined_long = pd.read_csv(args.combined_long_tsv, sep="\t")
    combined_long = BASE.normalise_combined_long(combined_long)

    detection_df, threshold_df = BASE.compute_detection_calls(
        dataframe=combined_long,
        threshold_mode=args.threshold_mode,
        min_detect_value=args.min_detect_value,
        sd_multiplier=args.sd_multiplier,
    )

    method_df = BASE.summarise_method_performance(detection_df, threshold_df)
    compact_df = BASE.build_compact_table(method_df)
    panel_species_df = BASE.build_panel_species_summary(detection_df, threshold_df)
    by_spike_df = BASE.summarise_detection_by_spike(detection_df)
    definitions_df = pd.DataFrame(BASE.METRIC_DEFINITIONS)
    plot_explanations_df = pd.DataFrame(BASE.REPORT_PLOT_EXPLANATIONS)

    reported_species_df = pd.DataFrame()
    reported_detection_df = pd.DataFrame()
    if args.reported_taxa_long_tsv:
        reported_taxa_path = Path(args.reported_taxa_long_tsv).expanduser().resolve()
        if reported_taxa_path.exists() and reported_taxa_path.stat().st_size > 0:
            reported_taxa_long = pd.read_csv(reported_taxa_path, sep="\t")
            reported_taxa_long = normalise_reported_taxa_long(reported_taxa_long)
            reported_taxa_long = choose_reported_taxa_metric(reported_taxa_long)
            reported_detection_df, reported_threshold_df = compute_reported_taxa_detection_calls(
                reported_taxa_df=reported_taxa_long,
                threshold_mode=args.threshold_mode,
                min_detect_value=args.min_detect_value,
                sd_multiplier=args.sd_multiplier,
            )
            expected_species_map = expected_species_map_from_combined_long(
                combined_long_df=combined_long,
            )
            reported_species_df = build_reported_species_summary_from_taxa(
                reported_detection_df=reported_detection_df,
                reported_threshold_df=reported_threshold_df,
                expected_species_map=expected_species_map,
            )

    if reported_species_df.empty:
        reported_species_df = BASE.build_reported_species_summary(
            detection_df=detection_df,
            threshold_df=threshold_df,
        )

    method_tsv = out_dir / "method_performance.tsv"
    compact_tsv = out_dir / "method_performance_compact.tsv"
    panel_species_tsv = out_dir / "method_panel_species_summary.tsv"
    reported_species_tsv = out_dir / "reported_offtarget_species_summary.tsv"
    reported_detection_tsv = out_dir / "reported_taxa_detection_calls.tsv"
    by_spike_tsv = out_dir / "method_performance_by_spike.tsv"
    definitions_tsv = out_dir / "metric_definitions.tsv"
    xlsx_path = out_dir / "method_performance.xlsx"
    page_html = out_dir / "method_performance.html"
    fragment_html = out_dir / "method_performance_fragment.html"

    method_df.to_csv(method_tsv, sep="\t", index=False)
    compact_df.to_csv(compact_tsv, sep="\t", index=False)
    panel_species_df.to_csv(panel_species_tsv, sep="\t", index=False)
    reported_species_df.to_csv(reported_species_tsv, sep="\t", index=False)
    if not reported_detection_df.empty:
        reported_detection_df.to_csv(reported_detection_tsv, sep="\t", index=False)
    else:
        pd.DataFrame().to_csv(reported_detection_tsv, sep="\t", index=False)
    by_spike_df.to_csv(by_spike_tsv, sep="\t", index=False)
    definitions_df.to_csv(definitions_tsv, sep="\t", index=False)

    with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
        compact_df.to_excel(writer, sheet_name="headline_table", index=False)
        panel_species_df.to_excel(writer, sheet_name="panel_species_summary", index=False)
        reported_species_df.to_excel(writer, sheet_name="reported_offtargets", index=False)
        method_df.to_excel(writer, sheet_name="full_method_table", index=False)
        by_spike_df.to_excel(writer, sheet_name="by_spike", index=False)
        definitions_df.to_excel(writer, sheet_name="definitions", index=False)
        plot_explanations_df.to_excel(writer, sheet_name="plot_interpretation", index=False)
        if not reported_detection_df.empty:
            reported_detection_df.to_excel(
                writer,
                sheet_name="reported_taxa_calls",
                index=False,
            )

    BASE.format_excel_sheet(
        workbook_path=xlsx_path,
        percentage_columns={
            "Sensitivity",
            "Specificity",
            "Precision",
            "F1",
            "False positive rate",
            "False negative rate",
            "Panel species recovery",
            "sensitivity",
            "recall",
            "true_positive_rate",
            "specificity",
            "false_positive_rate",
            "false_negative_rate",
            "precision",
            "negative_predictive_value",
            "accuracy",
            "balanced_accuracy",
            "f1_score",
            "youden_j",
            "detection_rate",
        },
        integer_columns={
            "Rank",
            "N expected species",
            "N found species",
            "N reported species",
            "N off-target species",
            "TP",
            "FN",
            "FP",
            "TN",
            "LOD50",
            "LOD95",
            "tp",
            "fn",
            "fp",
            "tn",
            "n_positive",
            "n_negative",
            "lod50_spike_n",
            "lod95_spike_n",
            "spike_n",
            "n_observations",
            "n_detected",
            "metric_value",
            "replicate",
        },
    )

    page_html.write_text(
        build_html_page(
            compact_df=compact_df,
            panel_species_df=panel_species_df,
            reported_species_df=reported_species_df,
            method_df=method_df,
            by_spike_df=by_spike_df,
            definitions_df=definitions_df,
            plot_explanations_df=plot_explanations_df,
        ),
        encoding="utf-8",
    )
    fragment_html.write_text(
        build_html_fragment(
            compact_df=compact_df,
            panel_species_df=panel_species_df,
            reported_species_df=reported_species_df,
            method_df=method_df,
            definitions_df=definitions_df,
            plot_explanations_df=plot_explanations_df,
        ),
        encoding="utf-8",
    )

    print(f"[INFO] Wrote: {method_tsv}")
    print(f"[INFO] Wrote: {compact_tsv}")
    print(f"[INFO] Wrote: {panel_species_tsv}")
    print(f"[INFO] Wrote: {reported_species_tsv}")
    print(f"[INFO] Wrote: {reported_detection_tsv}")
    print(f"[INFO] Wrote: {by_spike_tsv}")
    print(f"[INFO] Wrote: {definitions_tsv}")
    print(f"[INFO] Wrote: {xlsx_path}")
    print(f"[INFO] Wrote: {page_html}")
    print(f"[INFO] Wrote: {fragment_html}")


if __name__ == "__main__":
    main()
