
#!/usr/bin/env python3
"""
Build a combined spike-in benchmarking report with both tracked-target metrics and
stricter taxonomic-clean metrics that incorporate off-target species burden.

This script is intended to sit alongside the current spike-in summary outputs and
produce a single combined HTML report plus a formatted Excel workbook. It reads
the existing benchmark workbooks generated by the current pipeline and adds a
second set of "real-world" metrics that are closer to how a biologist would
experience the taxonomic output in practice.

Key ideas
---------
The existing tracked-target summaries ask whether the pre-specified target for a
workflow crossed threshold. They do not penalise a workflow for also reporting
multiple additional Plasmodium taxa. This script therefore reports both:

1. Tracked-target metrics
   Reused from the current summary workbooks.

2. Taxonomic-clean metrics
   Derived from the retained reported-taxa calls. These treat a positive
   observation as a clean recovery only if all expected panel species are
   recovered and no off-target taxa are reported above threshold. Negative
   observations are treated as taxonomically clean only if no taxa are reported
   above threshold.

Outputs
-------
- combined_real_world_report.html
- combined_real_world_report.xlsx
- multiple TSV support tables

The Excel workbook is formatted in the same general style as the earlier report
workbooks: dark blue headers, bold white header text, wrapped cells, filters,
and frozen top rows.

Notes
-----
- The script is intentionally conservative when constructing the taxonomic-clean
  metrics.
- For single-target runs represented as "single_target", any detected expected
  taxon counts as recovery of the expected panel.
- For mixed panels, all expected target labels must be recovered for a clean
  panel-level positive call.
"""

from __future__ import annotations

import argparse
import html
import math
from pathlib import Path
from typing import Iterable

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


HEADER_FILL = PatternFill(fill_type="solid", fgColor="1F4E79")
HEADER_FONT = Font(color="FFFFFF", bold=True)
TITLE_FONT = Font(size=14, bold=True)
SUBTITLE_FONT = Font(size=12, bold=True)
WRAP_ALIGN = Alignment(vertical="top", wrap_text=True)


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments.

    Returns
    -------
    argparse.Namespace
        Parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Create a combined spike-in benchmarking report with tracked-target "
            "and taxonomic-clean metrics."
        )
    )
    parser.add_argument(
        "--input_dir",
        default=None,
        help=(
            "Directory containing method_performance.xlsx, "
            "replicate_resolved_report.xlsx, and "
            "threshold_calibration_report.xlsx."
        ),
    )
    parser.add_argument(
        "--method_performance_xlsx",
        default=None,
        help="Path to method_performance.xlsx.",
    )
    parser.add_argument(
        "--replicate_report_xlsx",
        default=None,
        help="Path to replicate_resolved_report.xlsx.",
    )
    parser.add_argument(
        "--threshold_report_xlsx",
        default=None,
        help="Path to threshold_calibration_report.xlsx.",
    )
    parser.add_argument(
        "--out_dir",
        required=True,
        help="Output directory for the combined report.",
    )
    parser.add_argument(
        "--report_title",
        default="Combined ONT spike-in benchmark report",
        help="Report title used in the HTML and Excel outputs.",
    )
    return parser.parse_args()


def resolve_input_paths(args: argparse.Namespace) -> dict[str, Path]:
    """
    Resolve input workbook paths.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command-line arguments.

    Returns
    -------
    dict[str, Path]
        Mapping of workbook labels to resolved paths.
    """
    input_dir = Path(args.input_dir).expanduser().resolve() if args.input_dir else None

    def choose(explicit: str | None, default_name: str) -> Path:
        if explicit:
            return Path(explicit).expanduser().resolve()
        if input_dir is None:
            raise ValueError(
                f"No path supplied for {default_name} and --input_dir was not given."
            )
        return input_dir / default_name

    paths = {
        "method": choose(args.method_performance_xlsx, "method_performance.xlsx"),
        "replicate": choose(args.replicate_report_xlsx, "replicate_resolved_report.xlsx"),
        "threshold": choose(
            args.threshold_report_xlsx,
            "threshold_calibration_report.xlsx",
        ),
    }
    for label, path in paths.items():
        if not path.exists():
            raise FileNotFoundError(f"Required {label} workbook not found: {path}")
    return paths


def split_semicolon_values(value: object) -> list[str]:
    """
    Split a semicolon-delimited field into a cleaned list.

    Parameters
    ----------
    value : object
        Raw field value.

    Returns
    -------
    list[str]
        Cleaned values.
    """
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return []
    text = str(value).strip()
    if not text:
        return []
    return [item.strip() for item in text.split(";") if item.strip()]


def unique_join(values: Iterable[object]) -> str:
    """
    Join unique non-empty values using '; '.

    Parameters
    ----------
    values : Iterable[object]
        Values to join.

    Returns
    -------
    str
        Joined string.
    """
    seen = []
    for value in values:
        if value is None or (isinstance(value, float) and math.isnan(value)):
            continue
        text = str(value).strip()
        if text and text not in seen:
            seen.append(text)
    return "; ".join(seen)


def safe_rate(numerator: float, denominator: float) -> float | None:
    """
    Safely calculate a rate.

    Parameters
    ----------
    numerator : float
        Numerator.
    denominator : float
        Denominator.

    Returns
    -------
    float | None
        Rate, or None if the denominator is zero.
    """
    if denominator in (0, None) or pd.isna(denominator):
        return None
    return float(numerator) / float(denominator)


def load_workbook_sheets(path: Path) -> dict[str, pd.DataFrame]:
    """
    Load all sheets from an Excel workbook.

    Parameters
    ----------
    path : Path
        Workbook path.

    Returns
    -------
    dict[str, pd.DataFrame]
        Sheet-name to DataFrame mapping.
    """
    xls = pd.ExcelFile(path)
    return {sheet_name: pd.read_excel(path, sheet_name=sheet_name) for sheet_name in xls.sheet_names}


def build_observation_table(
    reported_taxa_calls: pd.DataFrame,
    panel_species_summary: pd.DataFrame,
) -> pd.DataFrame:
    """
    Collapse reported-taxa calls into one row per observation.

    Parameters
    ----------
    reported_taxa_calls : pd.DataFrame
        Replicate-resolved reported-taxa calls.
    panel_species_summary : pd.DataFrame
        Panel species summary sheet from method_performance.xlsx.

    Returns
    -------
    pd.DataFrame
        Observation-level table.
    """
    n_expected_lookup = (
        panel_species_summary[["Run", "N expected species"]]
        .dropna(subset=["Run"])
        .drop_duplicates()
        .rename(columns={"Run": "run_name", "N expected species": "n_expected_species"})
    )

    calls = reported_taxa_calls.copy()
    calls = calls.merge(n_expected_lookup, on="run_name", how="left")
    calls["n_expected_species"] = calls["n_expected_species"].fillna(1).astype(int)

    group_cols = [
        "workflow",
        "classifier",
        "run_name",
        "is_shuffled_control",
        "replicate",
        "spike_n_per_genome",
        "total_spike_n",
        "n_genomes",
        "is_positive",
        "is_negative",
        "expected_target_labels",
        "n_expected_species",
        "threshold_mode",
        "threshold_value",
    ]

    rows = []
    for group_values, group_df in calls.groupby(group_cols, dropna=False):
        row = dict(zip(group_cols, group_values))
        detected_df = group_df[group_df["detected"].fillna(False)].copy()

        row["n_reported_taxa_detected"] = int(detected_df["taxon_name"].nunique())
        row["n_off_target_taxa_detected"] = int(
            detected_df.loc[detected_df["is_off_target_taxon"].fillna(False), "taxon_name"].nunique()
        )
        row["n_expected_taxa_detected"] = int(
            detected_df.loc[detected_df["is_expected_taxon"].fillna(False), "taxon_name"].nunique()
        )

        expected_labels = split_semicolon_values(row["expected_target_labels"])
        matched_expected = set()

        if str(row["expected_target_labels"]).strip() == "single_target":
            if not detected_df.loc[detected_df["is_expected_taxon"].fillna(False)].empty:
                matched_expected.add("single_target")
        else:
            expected_set = set(expected_labels)
            for _, detected_row in detected_df.iterrows():
                matched_field = detected_row.get("matched_target_labels")
                matched_labels = split_semicolon_values(matched_field)
                for label in matched_labels:
                    if label in expected_set:
                        matched_expected.add(label)

                taxon_name = str(detected_row.get("taxon_name", "")).strip()
                if taxon_name in expected_set:
                    matched_expected.add(taxon_name)

            if not matched_expected and len(expected_set) == 1:
                if not detected_df.loc[detected_df["is_expected_taxon"].fillna(False)].empty:
                    matched_expected.add(next(iter(expected_set)))

        row["n_expected_panel_labels_detected"] = len(matched_expected)
        row["matched_expected_labels_detected"] = "; ".join(sorted(matched_expected))

        row["reported_taxa"] = unique_join(detected_df["taxon_name"].tolist())
        row["off_target_taxa"] = unique_join(
            detected_df.loc[
                detected_df["is_off_target_taxon"].fillna(False),
                "taxon_name",
            ].tolist()
        )

        row["any_expected_detected"] = row["n_expected_panel_labels_detected"] > 0
        row["all_expected_detected"] = (
            row["n_expected_panel_labels_detected"] >= row["n_expected_species"]
        )
        row["any_off_target_detected"] = row["n_off_target_taxa_detected"] > 0
        row["any_taxa_detected"] = row["n_reported_taxa_detected"] > 0
        row["clean_positive_call"] = (
            bool(row["all_expected_detected"]) and not bool(row["any_off_target_detected"])
        )

        if row["n_reported_taxa_detected"] > 0:
            row["taxonomic_precision_observation"] = (
                row["n_expected_panel_labels_detected"] / row["n_reported_taxa_detected"]
            )
        else:
            row["taxonomic_precision_observation"] = None

        rows.append(row)

    observation_df = pd.DataFrame(rows)
    observation_df["is_positive"] = observation_df["is_positive"].fillna(False).astype(bool)
    observation_df["is_negative"] = observation_df["is_negative"].fillna(False).astype(bool)
    observation_df["is_shuffled_control"] = (
        observation_df["is_shuffled_control"].fillna(False).astype(bool)
    )
    return observation_df


def summarise_real_world_metrics(
    observation_df: pd.DataFrame,
    group_cols: list[str],
) -> pd.DataFrame:
    """
    Summarise taxonomic-clean metrics.

    Parameters
    ----------
    observation_df : pd.DataFrame
        Observation-level table.
    group_cols : list[str]
        Columns used for grouping.

    Returns
    -------
    pd.DataFrame
        Summary table.
    """
    rows = []
    for group_values, group_df in observation_df.groupby(group_cols, dropna=False):
        row = dict(zip(group_cols, group_values))

        positives = group_df[group_df["is_positive"]]
        negatives = group_df[group_df["is_negative"]]

        n_positive = len(positives)
        n_negative = len(negatives)

        positive_any_expected = int(positives["any_expected_detected"].fillna(False).sum())
        positive_all_expected = int(positives["all_expected_detected"].fillna(False).sum())
        positive_clean = int(positives["clean_positive_call"].fillna(False).sum())
        positive_with_offtarget = int(positives["any_off_target_detected"].fillna(False).sum())

        negatives_clean = int((~negatives["any_taxa_detected"].fillna(False)).sum())
        negatives_any_taxa = int(negatives["any_taxa_detected"].fillna(False).sum())
        negatives_any_offtarget = int(
            negatives["any_off_target_detected"].fillna(False).sum()
        )

        row["n_observations"] = len(group_df)
        row["n_positive_observations"] = n_positive
        row["n_negative_observations"] = n_negative
        row["n_positive_any_expected"] = positive_any_expected
        row["n_positive_all_expected"] = positive_all_expected
        row["n_positive_clean"] = positive_clean
        row["n_positive_with_off_target"] = positive_with_offtarget
        row["n_negative_clean"] = negatives_clean
        row["n_negative_with_any_taxon"] = negatives_any_taxa
        row["n_negative_with_off_target"] = negatives_any_offtarget

        row["any_expected_sensitivity"] = safe_rate(positive_any_expected, n_positive)
        row["all_expected_sensitivity"] = safe_rate(positive_all_expected, n_positive)
        row["clean_sensitivity"] = safe_rate(positive_clean, n_positive)
        row["positive_off_target_rate"] = safe_rate(positive_with_offtarget, n_positive)
        row["taxonomic_specificity"] = safe_rate(negatives_clean, n_negative)
        row["taxonomic_false_positive_rate"] = safe_rate(negatives_any_taxa, n_negative)
        row["off_target_negative_rate"] = safe_rate(negatives_any_offtarget, n_negative)

        clean_precision = safe_rate(positive_clean, positive_clean + negatives_any_taxa)
        row["clean_precision"] = clean_precision
        if clean_precision is not None and row["clean_sensitivity"] not in (None, 0):
            denom = clean_precision + row["clean_sensitivity"]
            row["clean_f1"] = None if denom == 0 else (
                2 * clean_precision * row["clean_sensitivity"] / denom
            )
        else:
            row["clean_f1"] = None

        row["mean_reported_taxa_positive"] = (
            positives["n_reported_taxa_detected"].mean() if n_positive else None
        )
        row["mean_off_target_taxa_positive"] = (
            positives["n_off_target_taxa_detected"].mean() if n_positive else None
        )
        row["mean_taxonomic_precision_positive"] = (
            positives["taxonomic_precision_observation"].dropna().mean()
            if n_positive
            else None
        )
        row["median_off_target_taxa_positive"] = (
            positives["n_off_target_taxa_detected"].median() if n_positive else None
        )

        rows.append(row)

    summary_df = pd.DataFrame(rows)
    return summary_df


def build_polishing_comparison(
    run_real_world_summary: pd.DataFrame,
    run_performance: pd.DataFrame,
    reported_taxa_found: pd.DataFrame,
    off_target_by_run: pd.DataFrame,
) -> pd.DataFrame:
    """
    Compare Flye-only and Flye+Medaka multi-assembly outputs.

    Parameters
    ----------
    run_real_world_summary : pd.DataFrame
        Run-level taxonomic-clean summary.
    run_performance : pd.DataFrame
        Run-level tracked-target performance table.
    reported_taxa_found : pd.DataFrame
        Reported taxa found by run.
    off_target_by_run : pd.DataFrame
        Off-target taxa by run.

    Returns
    -------
    pd.DataFrame
        Polishing comparison table.
    """
    run_perf_small = run_performance[
        [
            "workflow",
            "run_name",
            "metric",
            "target_label",
            "sensitivity",
            "specificity",
            "precision",
            "f1_score",
            "lod50_spike_n",
            "lod95_spike_n",
        ]
    ].copy()

    expected_runs = run_real_world_summary[
        run_real_world_summary["workflow"].eq("multi_assembly")
    ].copy()

    comparisons = []
    panel_map = {
        "panel2": {
            "unpolished": "spikein_multi_flye_panel2",
            "polished": "spikein_multi_flye_medaka_panel2",
        },
        "panel3": {
            "unpolished": "spikein_multi_flye_panel3",
            "polished": "spikein_multi_flye_medaka_panel3",
        },
    }

    for panel_name, prefixes in panel_map.items():
        base_row = {"panel": panel_name}
        for state, prefix in prefixes.items():
            match = expected_runs[
                expected_runs["run_name"].astype(str).str.contains(prefix, na=False)
            ]
            if match.empty:
                continue
            run_name = match["run_name"].iloc[0]
            base_row[f"{state}_run_name"] = run_name

            row = match.iloc[0]
            for col in [
                "clean_sensitivity",
                "taxonomic_specificity",
                "positive_off_target_rate",
                "mean_reported_taxa_positive",
                "mean_off_target_taxa_positive",
                "clean_f1",
            ]:
                base_row[f"{state}_{col}"] = row.get(col)

            taxa_row = reported_taxa_found[
                reported_taxa_found["run_name"].eq(run_name)
            ]
            if not taxa_row.empty:
                base_row[f"{state}_n_taxa_found"] = int(taxa_row["n_taxa_found"].iloc[0])
                base_row[f"{state}_taxa_found"] = taxa_row["taxa_found"].iloc[0]

            off_row = off_target_by_run[off_target_by_run["run_name"].eq(run_name)]
            if not off_row.empty:
                base_row[f"{state}_n_off_target_taxa_detected"] = int(
                    off_row["n_off_target_taxa_detected"].iloc[0]
                )
                base_row[f"{state}_off_target_taxa_detected"] = off_row[
                    "off_target_taxa_detected"
                ].iloc[0]

            perf_rows = run_perf_small[run_perf_small["run_name"].eq(run_name)]
            if not perf_rows.empty:
                for _, perf_row in perf_rows.iterrows():
                    target = str(perf_row["target_label"]).replace(" ", "_")
                    base_row[f"{state}_{target}_sensitivity"] = perf_row["sensitivity"]
                    base_row[f"{state}_{target}_f1"] = perf_row["f1_score"]
                    base_row[f"{state}_{target}_lod50"] = perf_row["lod50_spike_n"]

        comparisons.append(base_row)

    comparison_df = pd.DataFrame(comparisons)
    if not comparison_df.empty:
        if {
            "unpolished_clean_sensitivity",
            "polished_clean_sensitivity",
        }.issubset(comparison_df.columns):
            comparison_df["delta_clean_sensitivity"] = (
                comparison_df["polished_clean_sensitivity"]
                - comparison_df["unpolished_clean_sensitivity"]
            )
        if {
            "unpolished_mean_off_target_taxa_positive",
            "polished_mean_off_target_taxa_positive",
        }.issubset(comparison_df.columns):
            comparison_df["delta_mean_off_target_taxa_positive"] = (
                comparison_df["polished_mean_off_target_taxa_positive"]
                - comparison_df["unpolished_mean_off_target_taxa_positive"]
            )
    return comparison_df


def add_sheet_from_dataframe(
    workbook: Workbook,
    sheet_name: str,
    dataframe: pd.DataFrame,
) -> None:
    """
    Add a formatted worksheet from a DataFrame.

    Parameters
    ----------
    workbook : Workbook
        Output workbook.
    sheet_name : str
        Sheet name.
    dataframe : pd.DataFrame
        Data to write.
    """
    worksheet = workbook.create_sheet(title=sheet_name[:31])

    if dataframe.empty:
        worksheet["A1"] = "No rows"
        return

    worksheet.append(list(dataframe.columns))
    for cell in worksheet[1]:
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = WRAP_ALIGN

    for _, row in dataframe.iterrows():
        values = []
        for value in row.tolist():
            if isinstance(value, pd.Timestamp):
                values.append(value.to_pydatetime())
            elif pd.isna(value):
                values.append(None)
            else:
                values.append(value)
        worksheet.append(values)

    worksheet.freeze_panes = "A2"
    worksheet.auto_filter.ref = worksheet.dimensions

    for column_cells in worksheet.columns:
        column_letter = get_column_letter(column_cells[0].column)
        max_length = 0
        for cell in column_cells:
            cell.alignment = WRAP_ALIGN
            text = "" if cell.value is None else str(cell.value)
            max_length = max(max_length, len(text))
        worksheet.column_dimensions[column_letter].width = min(max(max_length + 2, 12), 60)


def dataframe_to_html_table(dataframe: pd.DataFrame, max_rows: int | None = None) -> str:
    """
    Convert a DataFrame to an HTML table.

    Parameters
    ----------
    dataframe : pd.DataFrame
        Input table.
    max_rows : int | None
        Optional maximum number of rows to show.

    Returns
    -------
    str
        HTML table.
    """
    if dataframe.empty:
        return "<p class='muted'>No rows available.</p>"

    subset = dataframe.copy()
    if max_rows is not None:
        subset = subset.head(max_rows)

    return subset.to_html(
        index=False,
        border=0,
        classes="data-table",
        escape=True,
    )


def write_html_report(
    out_path: Path,
    title: str,
    tables: dict[str, tuple[pd.DataFrame, str, int | None]],
) -> None:
    """
    Write the combined HTML report.

    Parameters
    ----------
    out_path : Path
        Output HTML path.
    title : str
        Report title.
    tables : dict[str, tuple[pd.DataFrame, str, int | None]]
        Mapping of section title to (dataframe, note, max_rows).
    """
    sections = []
    for section_title, (dataframe, note, max_rows) in tables.items():
        sections.append(
            f"""
            <section class="report-section">
              <h2>{html.escape(section_title)}</h2>
              <p class="muted">{html.escape(note)}</p>
              <div class="table-wrap">
                {dataframe_to_html_table(dataframe, max_rows=max_rows)}
              </div>
            </section>
            """
        )

    html_text = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{html.escape(title)}</title>
  <style>
    body {{
      font-family: Arial, Helvetica, sans-serif;
      margin: 0;
      padding: 0;
      color: #1a1a1a;
      background: #f7f9fc;
    }}
    .container {{
      max-width: 1500px;
      margin: 0 auto;
      padding: 32px;
      background: #ffffff;
    }}
    h1, h2, h3 {{
      color: #1f4e79;
    }}
    .lede {{
      font-size: 16px;
      line-height: 1.5;
    }}
    .muted {{
      color: #666666;
    }}
    .note-box {{
      border-left: 4px solid #1f4e79;
      background: #f4f8fc;
      padding: 12px 16px;
      margin: 18px 0;
    }}
    .report-section {{
      margin-top: 32px;
    }}
    .table-wrap {{
      overflow-x: auto;
      border: 1px solid #dbe5f0;
      border-radius: 10px;
      margin-top: 14px;
      background: #ffffff;
    }}
    .data-table {{
      width: 100%;
      border-collapse: collapse;
      font-size: 14px;
    }}
    .data-table thead th {{
      position: sticky;
      top: 0;
      background: #1f4e79;
      color: white;
      text-align: left;
      padding: 10px 8px;
      white-space: nowrap;
      z-index: 2;
    }}
    .data-table td {{
      border-bottom: 1px solid #e6edf5;
      padding: 8px;
      vertical-align: top;
      white-space: normal;
      word-break: break-word;
      overflow-wrap: anywhere;
    }}
    .data-table tbody tr:nth-child(even) {{
      background: #fbfdff;
    }}
  </style>
</head>
<body>
  <div class="container">
    <h1>{html.escape(title)}</h1>
    <p class="lede">
      Combined spike-in benchmarking report merging tracked-target benchmark
      metrics with stricter taxonomic-clean metrics that penalise off-target
      species burden. The strict metrics are intended to provide a closer
      approximation to how a biologist would experience the report in practice.
    </p>
    <div class="note-box">
      <strong>How to read this report:</strong>
      The tracked-target sections reproduce the existing benchmark logic for the
      pre-specified target call. The taxonomic-clean sections add a second layer
      in which positives must recover all expected panel species without any
      off-target taxa, and negatives are considered clean only when no taxa are
      reported above threshold.
    </div>
    {''.join(sections)}
  </div>
</body>
</html>
"""
    out_path.write_text(html_text, encoding="utf-8")


def round_numeric_columns(dataframe: pd.DataFrame) -> pd.DataFrame:
    """
    Round floating-point columns for cleaner report output.

    Parameters
    ----------
    dataframe : pd.DataFrame
        Input DataFrame.

    Returns
    -------
    pd.DataFrame
        Rounded DataFrame.
    """
    out_df = dataframe.copy()
    for column in out_df.columns:
        if pd.api.types.is_float_dtype(out_df[column]):
            out_df[column] = out_df[column].round(3)
    return out_df


def main() -> None:
    """
    Run the report generation workflow.
    """
    args = parse_args()
    paths = resolve_input_paths(args)
    out_dir = Path(args.out_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    method_sheets = load_workbook_sheets(paths["method"])
    replicate_sheets = load_workbook_sheets(paths["replicate"])
    threshold_sheets = load_workbook_sheets(paths["threshold"])

    observation_df = build_observation_table(
        replicate_sheets["reported_taxa_calls"],
        method_sheets["panel_species_summary"],
    )

    run_real_world = summarise_real_world_metrics(
        observation_df,
        ["workflow", "classifier", "run_name"],
    )
    run_real_world = run_real_world.sort_values(
        by=["clean_f1", "taxonomic_specificity", "clean_sensitivity"],
        ascending=[False, False, False],
        na_position="last",
    ).reset_index(drop=True)

    workflow_real_world = summarise_real_world_metrics(
        observation_df,
        ["workflow", "classifier"],
    )
    workflow_real_world = workflow_real_world.sort_values(
        by=["clean_f1", "taxonomic_specificity", "clean_sensitivity"],
        ascending=[False, False, False],
        na_position="last",
    ).reset_index(drop=True)

    polishing_comparison = build_polishing_comparison(
        run_real_world_summary=run_real_world,
        run_performance=replicate_sheets["run_performance"],
        reported_taxa_found=replicate_sheets["reported_taxa_found"],
        off_target_by_run=replicate_sheets["off_target_by_run"],
    )

    definitions_df = pd.DataFrame(
        [
            {
                "term": "Tracked-target metrics",
                "definition": (
                    "Existing benchmark metrics that ask whether the single "
                    "pre-specified tracked target crossed threshold."
                ),
            },
            {
                "term": "Any-expected sensitivity",
                "definition": (
                    "Fraction of positive observations in which at least one "
                    "expected panel species was detected."
                ),
            },
            {
                "term": "All-expected sensitivity",
                "definition": (
                    "Fraction of positive observations in which all expected "
                    "panel species were detected, regardless of off-targets."
                ),
            },
            {
                "term": "Clean sensitivity",
                "definition": (
                    "Fraction of positive observations in which all expected "
                    "panel species were detected and no off-target taxa were "
                    "reported above threshold."
                ),
            },
            {
                "term": "Taxonomic specificity",
                "definition": (
                    "Fraction of negative observations with no taxa reported "
                    "above threshold."
                ),
            },
            {
                "term": "Taxonomic false-positive rate",
                "definition": (
                    "Fraction of negative observations with any taxon reported "
                    "above threshold."
                ),
            },
            {
                "term": "Positive off-target rate",
                "definition": (
                    "Fraction of positive observations containing at least one "
                    "off-target taxon above threshold."
                ),
            },
            {
                "term": "Clean precision",
                "definition": (
                    "Strict precision treating clean positive observations as "
                    "true positives and any taxon-positive negative observations "
                    "as false positives."
                ),
            },
            {
                "term": "Clean F1",
                "definition": (
                    "Harmonic mean of clean precision and clean sensitivity."
                ),
            },
        ]
    )

    tracked_note_df = pd.DataFrame(
        [
            {
                "note": (
                    "Tracked-target sensitivity, specificity, precision, F1, "
                    "and false-positive rate do not incorporate the broader "
                    "off-target species burden. These values answer a narrower "
                    "question than the taxonomic-clean metrics."
                )
            }
        ]
    )

    output_tables = {
        "executive_summary": round_numeric_columns(replicate_sheets["executive_summary"]),
        "tracked_target_headline": round_numeric_columns(method_sheets["headline_table"]),
        "tracked_panel_species_summary": round_numeric_columns(
            method_sheets["panel_species_summary"]
        ),
        "tracked_target_note": tracked_note_df,
        "workflow_real_world_summary": round_numeric_columns(workflow_real_world),
        "run_real_world_summary": round_numeric_columns(run_real_world),
        "observation_level_taxonomic_calls": round_numeric_columns(observation_df),
        "off_target_by_run": round_numeric_columns(replicate_sheets["off_target_by_run"]),
        "false_positive_taxa_by_tool": round_numeric_columns(
            replicate_sheets["fp_taxa_by_tool"]
        ),
        "false_positive_taxa_overall": round_numeric_columns(
            replicate_sheets["fp_taxa_overall"]
        ),
        "reported_taxa_found": round_numeric_columns(replicate_sheets["reported_taxa_found"]),
        "method_thresholds": round_numeric_columns(replicate_sheets["method_thresholds"]),
        "threshold_interpretive_bands": round_numeric_columns(
            threshold_sheets["interpretive_bands"]
        ),
        "threshold_recommendations": round_numeric_columns(
            threshold_sheets["recommendations"]
        ),
        "polishing_comparison": round_numeric_columns(polishing_comparison),
        "metric_definitions": definitions_df,
    }

    for sheet_name, dataframe in output_tables.items():
        dataframe.to_csv(
            out_dir / f"{sheet_name}.tsv",
            sep="\t",
            index=False,
        )

    workbook = Workbook()
    default_sheet = workbook.active
    workbook.remove(default_sheet)

    for sheet_name, dataframe in output_tables.items():
        add_sheet_from_dataframe(workbook, sheet_name, dataframe)

    excel_path = out_dir / "combined_real_world_report.xlsx"
    workbook.save(excel_path)

    html_tables = {
        "Tracked-target headline ranking": (
            output_tables["tracked_target_headline"],
            (
                "Existing tracked-target ranking. These metrics do not penalise "
                "extra off-target species in the broader taxonomic output."
            ),
            20,
        ),
        "Workflow-level taxonomic-clean summary": (
            output_tables["workflow_real_world_summary"],
            (
                "Workflow-level strict metrics incorporating off-target species "
                "burden into the practical interpretation."
            ),
            20,
        ),
        "Run-level taxonomic-clean summary": (
            output_tables["run_real_world_summary"],
            (
                "Run-level strict metrics. Clean sensitivity requires all "
                "expected panel species and no off-target taxa."
            ),
            20,
        ),
        "Polishing comparison": (
            output_tables["polishing_comparison"],
            (
                "Comparison of Flye-only and Flye+Medaka multi-assembly runs "
                "using both strict taxonomic-clean and tracked-target summaries."
            ),
            None,
        ),
        "Panel species summary": (
            output_tables["tracked_panel_species_summary"],
            (
                "Tracked-target panel summary from the current benchmark "
                "workbook."
            ),
            20,
        ),
        "Off-target taxa by run": (
            output_tables["off_target_by_run"],
            (
                "Run-level off-target burden derived from retained reported-taxa "
                "calls."
            ),
            20,
        ),
        "False-positive taxa by tool": (
            output_tables["false_positive_taxa_by_tool"],
            (
                "Taxa recurring in negative observations by workflow and "
                "classifier."
            ),
            20,
        ),
        "Interpretive signal bands": (
            output_tables["threshold_interpretive_bands"],
            (
                "Existing threshold-calibration interpretive bands retained for "
                "context."
            ),
            20,
        ),
        "Metric definitions": (
            output_tables["metric_definitions"],
            (
                "Definitions of the strict taxonomic-clean metrics added by this "
                "combined report."
            ),
            None,
        ),
    }

    write_html_report(
        out_path=out_dir / "combined_real_world_report.html",
        title=args.report_title,
        tables=html_tables,
    )

    print(f"Wrote report outputs to: {out_dir}")


if __name__ == "__main__":
    main()
